### ISSUE TITLE
Readme build instructions error

### ISSUE THREAD

**Issue by dineiar** [pacxx/pacxx#4]
I tried to follow the instructions in the Readme, but received the following error:
```
CMake Error: The source directory "/home/abc/pacxx" does not appear to contain CMakeLists.txt.
```
I solved it changing  
`cmake .. -DCMAKE_BUILD_TYPE=Release ...`
to  
`cmake ../llvm -DCMAKE_BUILD_TYPE=Release ...`

I believe this should be fixed in the `readme.md`.

**Comment by pacxx** [comment]
fixed, thanks!
